services:
  - type: web
    name: furnituretrack
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn funiture_track.wsgi:application
    envVars:
      - key: DATABASE_URL
        value:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
